name: MultiplyDrops
version: 0.1
author: Heathrxw
main: Heathrxw.Xenon.MultiplyDrops.MultiplyDrops
api-version: 1.15
commands:
  drops:
    description: Toggle multiplied block dropping
    usage: /drops